ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 8000
    onOpen: ignore
    visibility: public

tasks:
  - name: Dev
    command: |
      cp .env.example next/.env
      echo "NEXT_PUBLIC_BACKEND_URL=$(gp url 8000)" >> next/.env
      echo "NEXTAUTH_URL=$(gp url 3000)" >> next/.env
      echo "REWORKD_PLATFORM_FRONTEND_URL=$(gp url 3000)" >> next/.env
      docker-compose up

  - name: Prod
    command: |
      echo "NEXT_PUBLIC_BACKEND_URL=$(gp url 8000)" >> .ergomake/.env
      echo "NEXTAUTH_URL=$(gp url 3000)" >> .ergomake/.env
      echo "REWORKD_PLATFORM_FRONTEND_URL=$(gp url 3000)" >> .ergomake/.env
      docker-compose up
