version: '3.9'

services:
  next:
    env_file:
      - .env
    build:
      context: ../next
      dockerfile: ../.ergomake/next.Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL
        - NEXTAUTH_URL
        - DATABASE_URL
        - NEXTAUTH_SECRET
    ports:
      - "3000:3000"
    labels:
      dev.ergomake.env.replace-arg.NEXT_PUBLIC_BACKEND_URL: 'https://{{ services.platform.url }}'
      dev.ergomake.env.replace-arg.NEXTAUTH_URL: 'https://{{ services.next.url }}'

  docs:
    build:
      context: ../docs
      dockerfile: ../.ergomake/docs.Dockerfile
    ports:
      - "3001:3001"

  platform:
    build:
      context: ../platform
      dockerfile: ../.ergomake/platform.Dockerfile
    ports:
      - "8000:8000"
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3306"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
      REWORKD_PLATFORM_FF_MOCK_MODE_ENABLED: "true"
    labels:
      dev.ergomake.env.replace-arg.REWORKD_PLATFORM_FRONTEND_URL: 'https://{{ services.next.url }}'

  db:
    image: mysql:8.0
    build: ../db
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
